FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

{% for env_var in service.env_vars %}
ENV {{ env_var }}=""
{% endfor %}

EXPOSE {{ service.port }}

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "{{ service.port }}"]
